# TEMPORARILY USED until AuditBundle is compatible with ORM 3

name: Test

on:
    pull_request:

permissions:
    contents: read

jobs:
    test:
        name: PHP ${{ matrix.php-version }} + ${{ matrix.dependencies }} + ${{ matrix.variant }} (ORM 3)

        runs-on: ubuntu-latest

        continue-on-error: ${{ matrix.allowed-to-fail }}

        env:
            SYMFONY_REQUIRE: ${{matrix.symfony-require}}

        strategy:
            matrix:
                include:
                    - php-version: '8.3'
                      dependencies: highest
                      allowed-to-fail: false
                      symfony-require: 7.0.*
                      variant: symfony/symfony:"7.0.*"

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install PHP with extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  coverage: pcov
                  tools: composer:v2, flex

            - name: Add PHPUnit matcher
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Use gedmo-extension main branch
              run: composer require "gedmo/doctrine-extensions":"dev-main" --dev --no-update

            - name: Install variant
              if: matrix.variant != 'normal' && !startsWith(matrix.variant, 'symfony/symfony')
              run: composer require ${{ matrix.variant }} --no-update

            - name: Install Composer dependencies (${{ matrix.dependencies }})
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependencies }}

            - name: Run Tests with coverage
              run: make coverage

            - name: Send coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  files: build/logs/clover.xml
